kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-app
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: vishrut0/project:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu:  200m 
            memory: 512Mi
          limits:
            cpu:  400m 
            memory: 1Gi 
        volumeMounts:
        - mountPath: /mnt/data
          name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: web-pvc 
