kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-pvc
  namespace: web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage   