kind: PersistentVolume 
apiVersion: v1
metadata:
  name: web-pv
  namespace: web-app
  labels:
    app: local
spec: 
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  
  hostPath:
    path: /mnt/data   