apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: web-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=        # Base64 encoded value of "password"
  MYSQL_DATABASE: d29yZHByZXNz              # Base64 encoded value of "wordpress"
  MYSQL_USER: dXNlcm5hbWU=                  # Base64 encoded value of "username"
  MYSQL_PASSWORD: cGFzc3dvcmQ=              # Base64 encoded value of "password"