apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web-app
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP