apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: nginx
spec:
  template:
    spec:
      containers:
      - name: pi
        image: bash:latest
        command: ["sh", "-c", "echo hello! && sleep 14"]
      restartPolicy: Never        
