kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tws-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.31.2
  
- role: worker
  image: kindest/node:v1.31.2

- role: worker
  image: kindest/node:v1.31.2

- role: worker
  image: kindest/node:v1.31.2
