kind: PersistentVolume 
apiVersion: v1
metadata:
  name: local-pv
  namespace: apache
  labels:
    app: local
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  
  hostPath:
    path: /home/elox/Documents/kubernetes/volumes/apache