kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage   