apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress-app
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=        # Base64 encoded value of "password"
  DATABASE: d29yZHByZXNz              # Base64 encoded value of "wordpress"
  USER: dXNlcm5hbWU=                  # Base64 encoded value of "username"
  USER_PASSWORD: cGFzc3dvcmQ=              # Base64 encoded value of "password"