apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: wordpress-app
  labels:
    app: wordpress-app
spec:
  selector:
    app: wordpress-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306  
  type: ClusterIP