kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress-webapp
  namespace: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app  
  template:
    metadata:
      labels:
        app: wordpress-app  
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: PASSWORD
        - name: WORDPRESS_DB_USER
          value: username
        ports:
        - containerPort: 80
